# Generated by Django 4.1 on 2022-08-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productgroup'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcategory'),
        ),
    ]
